
defaults:
  - identify_associations_bayes_cat

batch_size: 10

num_refits: 10

target_dataset: random.catagorical.drug
target_value: 1
save_refits: True

model:
  num_hidden:
    - 100 
  num_latent: 10 

training_loop:
  lr: 1e-4
  num_epochs: 40
